version: "3.9"

services:

#NodeJS-PoolController-dashPanel
  #Core
  nodeJS-poolController-dashPanel:
    build: ./default
    restart: on-failure
    network_mode: host
    ports:
      -80:80
      -443:443
