version: "3.9"

services:

#NodeJS-PoolController
  #Core
  nodeJS-poolController:
    build: ./default
    restart: on-failure
    privileged: true
    network_mode: host
    ports:
      -4200:4200
